### ISSUE TITLE
We need a way to set font-szie globally

### ISSUE THREAD

**Issue by lamodots** [MEDkids/.github#1]
Currently we are defining base font size for each page by setting the rule
  ```css
          html {
      font-size:16px;
    }
        
    ```
    This is redundant , it will be nice if we can set it in one place
